// Plays the sound generated by the console: one buffer of 735 stereo
// samples at 44100 Hz per emulated frame, scheduled with Web Audio.

const SampleRate = 44100;
const SamplesPerFrame = 735;
const TargetLatency = 0.06;   // seconds of audio queued ahead
const MaximumLatency = 0.2;   // beyond this, buffers are dropped to catch up

export class AudioOutput {
  private context: AudioContext | null = null;
  private gain: GainNode | null = null;
  private nextTime = 0;
  private volume = 1;
  private muted = false;

  /** must be called from a user gesture (click, key press) for browsers to allow audio */
  start(): void {
    if (!this.context) {
      try {
        this.context = new AudioContext({ sampleRate: SampleRate, latencyHint: "interactive" });
      } catch {
        this.context = new AudioContext();
      }
      this.gain = this.context.createGain();
      this.gain.connect(this.context.destination);
      this.applyVolume();
    }
    if (this.context.state === "suspended") void this.context.resume();
  }

  get isRunning(): boolean {
    return this.context !== null && this.context.state === "running";
  }

  setVolume(volume: number): void {
    this.volume = Math.min(Math.max(volume, 0), 1);
    this.applyVolume();
  }

  setMuted(muted: boolean): void {
    this.muted = muted;
    this.applyVolume();
  }

  get isMuted(): boolean { return this.muted; }

  private applyVolume(): void {
    // same curve as the desktop emulator: perceived volume is squared
    if (this.gain) this.gain.gain.value = this.muted ? 0 : this.volume * this.volume;
  }

  /** queues one frame of audio (1470 interleaved int16 samples) */
  pushFrame(samples: Int16Array): void {
    const context = this.context;
    if (!context || context.state !== "running") return;

    const now = context.currentTime;
    if (this.nextTime < now + 0.005) this.nextTime = now + TargetLatency;
    if (this.nextTime > now + MaximumLatency) return;

    const buffer = context.createBuffer(2, SamplesPerFrame, SampleRate);
    const left = buffer.getChannelData(0);
    const right = buffer.getChannelData(1);
    for (let i = 0; i < SamplesPerFrame; i++) {
      left[i] = samples[2 * i] / 32768;
      right[i] = samples[2 * i + 1] / 32768;
    }
    const source = context.createBufferSource();
    source.buffer = buffer;
    source.connect(this.gain!);
    source.start(this.nextTime);
    this.nextTime += SamplesPerFrame / SampleRate;
  }

  /** forgets the queued timeline, e.g. after pausing */
  resync(): void {
    this.nextTime = 0;
  }
}
